remote:
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/areal-comparison
  naomi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-data-orderly
  naomi2:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-orderly-naomi2
  malawi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/mwi-hiv-orderly
  fertility:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility

fields:
  requester:
    required: false
  author:
    required: false

global_resources:
  global
